// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { detectAndSaveApiV1DiffDetectSavePost, detectDifferencesApiV1DiffDetectPost, detectDifferencesMetaApiV1DiffDetectMetaPost, healthCheckHealthGet, type Options, rootGet } from '../sdk.gen';
import type { DetectAndSaveApiV1DiffDetectSavePostData, DetectAndSaveApiV1DiffDetectSavePostError, DetectAndSaveApiV1DiffDetectSavePostResponse, DetectDifferencesApiV1DiffDetectPostData, DetectDifferencesApiV1DiffDetectPostError, DetectDifferencesApiV1DiffDetectPostResponse, DetectDifferencesMetaApiV1DiffDetectMetaPostData, DetectDifferencesMetaApiV1DiffDetectMetaPostError, DetectDifferencesMetaApiV1DiffDetectMetaPostResponse, HealthCheckHealthGetData, HealthCheckHealthGetResponse, RootGetData } from '../types.gen';

/**
 * 检测图片差异
 *
 * 上传游戏截图，自动提取上下两张图片并检测差异区域，返回标记后的图片（base64 编码）
 */
export const detectDifferencesApiV1DiffDetectPostMutation = (options?: Partial<Options<DetectDifferencesApiV1DiffDetectPostData>>): UseMutationOptions<DetectDifferencesApiV1DiffDetectPostResponse, AxiosError<DetectDifferencesApiV1DiffDetectPostError>, Options<DetectDifferencesApiV1DiffDetectPostData>> => {
    const mutationOptions: UseMutationOptions<DetectDifferencesApiV1DiffDetectPostResponse, AxiosError<DetectDifferencesApiV1DiffDetectPostError>, Options<DetectDifferencesApiV1DiffDetectPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await detectDifferencesApiV1DiffDetectPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * 检测图片差异（仅元数据）
 *
 * 上传游戏截图，仅返回差异区域的元数据，不返回图片
 */
export const detectDifferencesMetaApiV1DiffDetectMetaPostMutation = (options?: Partial<Options<DetectDifferencesMetaApiV1DiffDetectMetaPostData>>): UseMutationOptions<DetectDifferencesMetaApiV1DiffDetectMetaPostResponse, AxiosError<DetectDifferencesMetaApiV1DiffDetectMetaPostError>, Options<DetectDifferencesMetaApiV1DiffDetectMetaPostData>> => {
    const mutationOptions: UseMutationOptions<DetectDifferencesMetaApiV1DiffDetectMetaPostResponse, AxiosError<DetectDifferencesMetaApiV1DiffDetectMetaPostError>, Options<DetectDifferencesMetaApiV1DiffDetectMetaPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await detectDifferencesMetaApiV1DiffDetectMetaPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * 检测图片差异并保存结果
 *
 * 上传游戏截图，检测差异并将结果图片保存到指定目录
 */
export const detectAndSaveApiV1DiffDetectSavePostMutation = (options?: Partial<Options<DetectAndSaveApiV1DiffDetectSavePostData>>): UseMutationOptions<DetectAndSaveApiV1DiffDetectSavePostResponse, AxiosError<DetectAndSaveApiV1DiffDetectSavePostError>, Options<DetectAndSaveApiV1DiffDetectSavePostData>> => {
    const mutationOptions: UseMutationOptions<DetectAndSaveApiV1DiffDetectSavePostResponse, AxiosError<DetectAndSaveApiV1DiffDetectSavePostError>, Options<DetectAndSaveApiV1DiffDetectSavePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await detectAndSaveApiV1DiffDetectSavePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const healthCheckHealthGetQueryKey = (options?: Options<HealthCheckHealthGetData>) => createQueryKey('healthCheckHealthGet', options);

/**
 * 健康检查
 *
 * 检查服务健康状态
 */
export const healthCheckHealthGetOptions = (options?: Options<HealthCheckHealthGetData>) => queryOptions<HealthCheckHealthGetResponse, AxiosError<DefaultError>, HealthCheckHealthGetResponse, ReturnType<typeof healthCheckHealthGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthCheckHealthGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthCheckHealthGetQueryKey(options)
});

export const rootGetQueryKey = (options?: Options<RootGetData>) => createQueryKey('rootGet', options);

/**
 * API 根路径
 *
 * API 根路径，返回服务基本信息
 */
export const rootGetOptions = (options?: Options<RootGetData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof rootGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await rootGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: rootGetQueryKey(options)
});
