// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DetectAndSaveApiV1DiffDetectSavePostData, DetectAndSaveApiV1DiffDetectSavePostErrors, DetectAndSaveApiV1DiffDetectSavePostResponses, DetectDifferencesApiV1DiffDetectPostData, DetectDifferencesApiV1DiffDetectPostErrors, DetectDifferencesApiV1DiffDetectPostResponses, DetectDifferencesMetaApiV1DiffDetectMetaPostData, DetectDifferencesMetaApiV1DiffDetectMetaPostErrors, DetectDifferencesMetaApiV1DiffDetectMetaPostResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses, RootGetData, RootGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 检测图片差异
 *
 * 上传游戏截图，自动提取上下两张图片并检测差异区域，返回标记后的图片（base64 编码）
 */
export const detectDifferencesApiV1DiffDetectPost = <ThrowOnError extends boolean = false>(options: Options<DetectDifferencesApiV1DiffDetectPostData, ThrowOnError>) => (options.client ?? client).post<DetectDifferencesApiV1DiffDetectPostResponses, DetectDifferencesApiV1DiffDetectPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/v1/diff/detect',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * 检测图片差异（仅元数据）
 *
 * 上传游戏截图，仅返回差异区域的元数据，不返回图片
 */
export const detectDifferencesMetaApiV1DiffDetectMetaPost = <ThrowOnError extends boolean = false>(options: Options<DetectDifferencesMetaApiV1DiffDetectMetaPostData, ThrowOnError>) => (options.client ?? client).post<DetectDifferencesMetaApiV1DiffDetectMetaPostResponses, DetectDifferencesMetaApiV1DiffDetectMetaPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/v1/diff/detect/meta',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * 检测图片差异并保存结果
 *
 * 上传游戏截图，检测差异并将结果图片保存到指定目录
 */
export const detectAndSaveApiV1DiffDetectSavePost = <ThrowOnError extends boolean = false>(options: Options<DetectAndSaveApiV1DiffDetectSavePostData, ThrowOnError>) => (options.client ?? client).post<DetectAndSaveApiV1DiffDetectSavePostResponses, DetectAndSaveApiV1DiffDetectSavePostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/api/v1/diff/detect/save',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * 健康检查
 *
 * 检查服务健康状态
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/health',
    ...options
});

/**
 * API 根路径
 *
 * API 根路径，返回服务基本信息
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/',
    ...options
});
