// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * Body_detect_and_save_api_v1_diff_detect_save_post
 */
export type BodyDetectAndSaveApiV1DiffDetectSavePost = {
    /**
     * File
     *
     * 游戏截图文件
     */
    file: Blob | File;
    /**
     * Output Dir
     *
     * 输出目录路径
     */
    output_dir?: string;
    /**
     * Filename Prefix
     *
     * 文件名前缀
     */
    filename_prefix?: string;
    /**
     * Min Area
     *
     * 最小差异区域面积
     */
    min_area?: number;
    /**
     * Diff Threshold
     *
     * 差异阈值
     */
    diff_threshold?: number;
};

/**
 * Body_detect_differences_api_v1_diff_detect_post
 */
export type BodyDetectDifferencesApiV1DiffDetectPost = {
    /**
     * File
     *
     * 游戏截图文件
     */
    file: Blob | File;
    /**
     * Min Area
     *
     * 最小差异区域面积
     */
    min_area?: number;
    /**
     * Diff Threshold
     *
     * 差异阈值
     */
    diff_threshold?: number;
};

/**
 * Body_detect_differences_meta_api_v1_diff_detect_meta_post
 */
export type BodyDetectDifferencesMetaApiV1DiffDetectMetaPost = {
    /**
     * File
     *
     * 游戏截图文件
     */
    file: Blob | File;
    /**
     * Min Area
     *
     * 最小差异区域面积
     */
    min_area?: number;
    /**
     * Diff Threshold
     *
     * 差异阈值
     */
    diff_threshold?: number;
};

/**
 * DiffMetaResponse
 *
 * 差异检测响应（仅元数据，不包含图片）
 */
export type DiffMetaResponse = {
    /**
     * Difference Count
     *
     * 检测到的差异数量
     */
    difference_count: number;
    /**
     * Differences
     *
     * 差异区域列表
     */
    differences?: Array<DifferenceRegion>;
    /**
     * 处理后的图片尺寸
     */
    image_size: ImageSize;
};

/**
 * DiffResponse
 *
 * 差异检测响应（包含 base64 图片）
 */
export type DiffResponse = {
    /**
     * Difference Count
     *
     * 检测到的差异数量
     */
    difference_count: number;
    /**
     * Differences
     *
     * 差异区域列表
     */
    differences?: Array<DifferenceRegion>;
    /**
     * 处理后的图片尺寸
     */
    image_size: ImageSize;
    /**
     * Marked Image Base64
     *
     * 标记后的拼接图片（base64 编码）
     */
    marked_image_base64?: string | null;
    /**
     * Heatmap Base64
     *
     * 差异热力图（base64 编码）
     */
    heatmap_base64?: string | null;
    /**
     * Image1 Base64
     *
     * 标记后的图片1（base64 编码）
     */
    image1_base64?: string | null;
    /**
     * Image2 Base64
     *
     * 标记后的图片2（base64 编码）
     */
    image2_base64?: string | null;
};

/**
 * DiffSaveResponse
 *
 * 差异检测响应（保存文件版本）
 */
export type DiffSaveResponse = {
    /**
     * Difference Count
     *
     * 检测到的差异数量
     */
    difference_count: number;
    /**
     * Differences
     *
     * 差异区域列表
     */
    differences?: Array<DifferenceRegion>;
    /**
     * 保存的文件路径
     */
    saved_files: SavedFiles;
};

/**
 * DifferenceRegion
 *
 * 单个差异区域信息
 */
export type DifferenceRegion = {
    /**
     * Index
     *
     * 差异区域编号
     */
    index: number;
    /**
     * X
     *
     * 差异区域左上角 X 坐标
     */
    x: number;
    /**
     * Y
     *
     * 差异区域左上角 Y 坐标
     */
    y: number;
    /**
     * Width
     *
     * 差异区域宽度
     */
    width: number;
    /**
     * Height
     *
     * 差异区域高度
     */
    height: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * 健康检查响应
 */
export type HealthResponse = {
    /**
     * Status
     *
     * 服务状态
     */
    status: string;
    /**
     * Version
     *
     * API 版本
     */
    version: string;
};

/**
 * ImageSize
 *
 * 图片尺寸信息
 */
export type ImageSize = {
    /**
     * Width
     *
     * 图片宽度
     */
    width: number;
    /**
     * Height
     *
     * 图片高度
     */
    height: number;
};

/**
 * SavedFiles
 *
 * 保存的文件路径信息
 */
export type SavedFiles = {
    /**
     * Combined
     *
     * 拼接结果图片路径
     */
    combined: string;
    /**
     * Heatmap
     *
     * 热力图路径
     */
    heatmap: string;
    /**
     * Image1 Marked
     *
     * 标记后的图片1路径
     */
    image1_marked: string;
    /**
     * Image2 Marked
     *
     * 标记后的图片2路径
     */
    image2_marked: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type DetectDifferencesApiV1DiffDetectPostData = {
    body: BodyDetectDifferencesApiV1DiffDetectPost;
    path?: never;
    query?: never;
    url: '/api/v1/diff/detect';
};

export type DetectDifferencesApiV1DiffDetectPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DetectDifferencesApiV1DiffDetectPostError = DetectDifferencesApiV1DiffDetectPostErrors[keyof DetectDifferencesApiV1DiffDetectPostErrors];

export type DetectDifferencesApiV1DiffDetectPostResponses = {
    /**
     * Successful Response
     */
    200: DiffResponse;
};

export type DetectDifferencesApiV1DiffDetectPostResponse = DetectDifferencesApiV1DiffDetectPostResponses[keyof DetectDifferencesApiV1DiffDetectPostResponses];

export type DetectDifferencesMetaApiV1DiffDetectMetaPostData = {
    body: BodyDetectDifferencesMetaApiV1DiffDetectMetaPost;
    path?: never;
    query?: never;
    url: '/api/v1/diff/detect/meta';
};

export type DetectDifferencesMetaApiV1DiffDetectMetaPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DetectDifferencesMetaApiV1DiffDetectMetaPostError = DetectDifferencesMetaApiV1DiffDetectMetaPostErrors[keyof DetectDifferencesMetaApiV1DiffDetectMetaPostErrors];

export type DetectDifferencesMetaApiV1DiffDetectMetaPostResponses = {
    /**
     * Successful Response
     */
    200: DiffMetaResponse;
};

export type DetectDifferencesMetaApiV1DiffDetectMetaPostResponse = DetectDifferencesMetaApiV1DiffDetectMetaPostResponses[keyof DetectDifferencesMetaApiV1DiffDetectMetaPostResponses];

export type DetectAndSaveApiV1DiffDetectSavePostData = {
    body: BodyDetectAndSaveApiV1DiffDetectSavePost;
    path?: never;
    query?: never;
    url: '/api/v1/diff/detect/save';
};

export type DetectAndSaveApiV1DiffDetectSavePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DetectAndSaveApiV1DiffDetectSavePostError = DetectAndSaveApiV1DiffDetectSavePostErrors[keyof DetectAndSaveApiV1DiffDetectSavePostErrors];

export type DetectAndSaveApiV1DiffDetectSavePostResponses = {
    /**
     * Successful Response
     */
    200: DiffSaveResponse;
};

export type DetectAndSaveApiV1DiffDetectSavePostResponse = DetectAndSaveApiV1DiffDetectSavePostResponses[keyof DetectAndSaveApiV1DiffDetectSavePostResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
